name: 'cadence'
version: '0.1.0'
config-version: 2

# Require dbt 1.8.0 or higher
require-dbt-version: [">=1.8.0"]

profile: 'cadence'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  cadence:
    +materialized: table
    
    # Guardian (core monitoring logic)
    guardian:
      +schema: cadence_metadata
      
      metadata:
        +materialized: table
        +on_schema_change: "append_new_columns"
        
      detection:
        actual_batches:
          +materialized: ephemeral
        batch_gaps:
          +materialized: table
          
      alerts:
        +materialized: table
    
    # Examples (demo data)
    examples:
      +schema: cadence_examples
      +materialized: table

# Global variables
vars:
  cadence:
    default_frequency: 'hourly'

# Seeds configuration
seeds:
  cadence:
    +schema: cadence_metadata
    example_cadence_config:
      +column_types:
        start_date: date
        enabled: boolean
