name: 'cadence'
version: '0.1.0'
config-version: 2

# Project profile (points to profiles.yml)
profile: 'cadence'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build directory
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  cadence:
    # Core cadence models
    +materialized: table
    
    # Guardian metadata tracking
    guardian:
      +schema: cadence_metadata
      +materialized: incremental
      +on_schema_change: "append_new_columns"
    
    # Example/demo models
    examples:
      +schema: cadence_examples
      +materialized: view

# Vars (configuration globale)
vars:
  cadence:
    # Default cadence frequency
    default_frequency: 'hourly'
